checkpoint_path: /media/alergn/hdd/github/dcec-tcd-voip/models/voiceMOS/Wav2VecSmall/wav2vec_small.pt
current_level:
- 1
- 2
emb_dim: 256
experiment_name: Training
freeze_all: false
freeze_convnet: true
lr: 0.0001
lr_decay_factor: 0.99
lr_decay_step: 30
margin: 0.2
num_epochs: 50
num_workers: 6
out_dir: train_triplet
patience: 1
root: /media/alergn/hdd/datasets/audio/speech/LibriSpeechDeg/
sampling_rate: 16000
ssl_out_dim: 768
test_bs: 1
train_bs: 2
train_df: data/train.csv
training_script: src.training.train_triplet
trim: true
val_bs: 2
valid_df: data/valid.csv
