# Root where to store datasets (default ./data)
root: '/media/alergn/hdd/datasets/audio/speech/LibriSpeech'

# Training (Nomad train and valid sets) path settings
in_dir_train: 'train-clean-100'
in_dir_train_wav: 'train-clean-100-wav'
out_dir_train: 'train-clean-100-degraded-dummy'

# Test (degradation intensity) path settings
in_dir_test: 'test-clean'
in_dir_test_wav: 'test-clean-wav'
out_dir_test: 'test-clean-degraded-dummy'

# Sampling rate
sr: 16000

# Bitrate
mp3_train: ['8k', '16k', '32k', '64k', '128k']
mp3_test: ['2k', '5k', '9k', '12k', '18k', '20k', '24k', '30k', '36k', '42k', '46k', '50k', '55k', '65k', '68k', '72k', '90k', '100k', '110k', '130k', '150k', '160k', '180k', '200k', '210k']

# Bitrate
opus_train: ['8k', '16k', '32k', '64k', '128k']
opus_test: ['2k', '5k', '9k', '12k', '18k', '20k', '24k', '30k', '36k', '42k', '46k', '50k', '55k', '65k', '68k', '72k', '90k', '100k', '110k', '130k', '150k', '160k', '180k', '200k', '210k']

# Percentage of samples to clip
clip_train: [5, 10, 25, 40, 60]
clip_test: [2, 5, 6, 8, 11, 12, 15, 18, 20, 22, 24, 27, 29, 30, 33, 35, 37, 39, 41, 50, 62]

# SNR dB
root_noise: '/media/alergn/hdd/datasets/audio/speech/'
noise_train: [0, 8, 15, 25, 40]
noise_dir_train: 'MS-SNSD/noise_train'
noise_test: [1, 3, 4, 6, 9, 10, 12, 14, 16, 19, 20, 22, 24, 26, 28, 30, 32, 33, 35, 37, 39, 42, 44, 46, 50]
noise_dir_test: 'MS-SNSD/noise_test'

# Unseen degradations
# Reverb (%)
reverb: [1, 3, 6, 7, 9, 10, 12, 14, 16, 19, 20, 22, 24, 26, 28, 32, 36, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]

# Vorbis (quality)
vorbis: ['0', '1', '3', '5', '7', '9']