in_dir: '/media/alergn/hdd/datasets/audio/speech/LibriSpeech/test-clean'
librispeech_wav: '/media/alergn/hdd/datasets/audio/speech/LibriSpeech/test-clean-wav'
out_dir: '/media/alergn/hdd/datasets/audio/speech/LibriSpeechDegTestRefUnique/'

#in_dir: './data/in_test'
#out_dir: './data/out_test'

sr: 16000

# Bitrate
mp3_params: ['8k', '16k', '32k', '64k', '128k']
MP3: ['2k', '5k', '8k', '12k', '18k', '20k', '24k', '30k', '36k', '42k', '46k', '50k', '55k', '65k', '68k', '72k', '90k', '100k', '110k', '130k', '150k', '160k', '180k', '200k', '210k']
#MP3: ['10k', '15k', '20k', '25k', '30k', '35k', '40k', '45k', '50k', '55k']

# Bitrate
opus_params: ['8k', '16k', '32k', '64k', '128k']
OPUS: ['2k', '5k', '8k', '12k', '18k', '20k', '24k', '30k', '36k', '42k', '46k', '50k', '55k', '65k', '68k', '72k', '90k', '100k', '110k', '130k', '150k', '160k', '180k', '200k', '210k']
#OPUS: ['2k', '6k', '20k', '50k', '100k', '256k']
#OPUS: ['10k', '15k', '20k', '25k', '30k', '35k', '40k', '45k', '50k', '55k']

# Percentage of samples to clip
clip_params: [5, 10, 25, 40, 60]
CLIP: [2, 5, 6, 8, 10, 12, 15, 18, 20, 22, 24, 27, 29, 30, 33, 35, 37, 39, 41, 50, 60]
#CLIP: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

# SNR dB
noise_params: [0, 8, 15, 25, 40]
noise_dir: '/media/alergn/hdd/datasets/audio/speech/MS-SNSD/noise_train'
NOISE: [1, 3, 4, 6, 9, 10, 12, 14, 16, 19, 20, 22, 24, 26, 28, 30, 32, 33, 35, 37, 39, 42, 44, 46, 50]
#NOISE: [4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
noise_dir_test: '/media/alergn/hdd/datasets/audio/speech/MS-SNSD/noise_test'

# Unseen degradations
# Reverb (%)
REVERB: [1, 3, 6, 7, 9, 10, 12, 14, 16, 19, 20, 22, 24, 26, 28, 32, 36, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
#REVERB: [5, 7, 9, 11, 13, 15, 17, 19, 21, 23]

# Vorbis (quality)
#vorbis_params: ['2k', '6k', '20k', '50k', '100k', '256k']
VORBIS: ['0', '1', '3', '5', '7', '9']
#VORBIS: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']