# ****** EXPERIMENT PARAMETERS *******
# Feature choice
experiment_name: "quality_nmr"
out_dir: "./experiments/triplet"
training_script: "src.training.train_triplet"

# Feature parameters
sampling_rate: 16000

# Hyper parameter
num_workers: 6

# Early stopping
patience: 20

# wav2vec pretrained model path
checkpoint_path: ./pt-models/wav2vec_small.pt

# W2V FINETUNE TRANSFORMER (1,2)
nomad_model_path: ./pt-models/nomad_best_model.pt

ssl_out_dim: 768

# Quality embedding triplet loss 
emb_dim: 256
margin: 0.2

# Evaluation embedding parameters
non_match_dir: /path/to/non-matching-references
test_db_file: ./data/test_quality_nogs.csv
test_db_file_fr: ./data/test_quality_nogs.csv
db: null
conds: null
test_root_wav: /path/to/waves/

# Evaluation monotonocity rank
test_mono_data: './data/test_degradation_intensity_new.csv'
test_mono_wav: '/path/to/Degraded Librispeech test'

# Eval orig w2v (Set true to evaluate w2v feature vectors)
eval_w2v: False

current_level: 
  - 1
  - 2

# Do not trim for testing
trim: False