# ****** EXPERIMENT PARAMETERS *******
# Feature choice
experiment_name: "Training"
out_dir: "train-triplet"
training_script: "src.training.train_triplet"

# Path to csv file and root dir (relative to main file)
root: "/path/to/Degraded Librispeech"
train_df: data/train.csv
valid_df: data/valid.csv

# Feature parameters
sampling_rate: 16000

# Hyper parameter
train_bs: 8
val_bs: 8
test_bs: 1
lr: 0.0001
lr_decay_factor: 0.99
lr_decay_step: 30
num_epochs: 50
num_workers: 6
emb_dim: 256

# Early stopping
patience: 200
 
# wav2vec pretrained model path
checkpoint_path: "pt-models/wav2vec_small.pt"
ssl_out_dim: 768
margin: 0.2

# Choose feature extraction or partial finetuning
freeze_convnet: True
freeze_all: False

# Level db ### 1 EASY Sampling, ### 2 HARD Sampling, ### 1,2 both
current_level: 
  - 1
  - 2

# Training is done by trimming to 10 secs each training file that is longer, not used during testing
trim: True